// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyUn-nBdzuhDiihtcF2tLU_xWh2Wd76B8',
    appId: '1:870510802843:web:c1baf051f5b0e64344d33e',
    messagingSenderId: '870510802843',
    projectId: 'to-do-application-442e7',
    authDomain: 'to-do-application-442e7.firebaseapp.com',
    storageBucket: 'to-do-application-442e7.appspot.com',
    measurementId: 'G-8Y46F3CX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirvzUicropdd-c-XlG5kp47hHc0t5094',
    appId: '1:870510802843:android:1e568e1e9887d61244d33e',
    messagingSenderId: '870510802843',
    projectId: 'to-do-application-442e7',
    storageBucket: 'to-do-application-442e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkuEwcX4ul-tlpUVOLB9y_3Eoq4guU1UA',
    appId: '1:870510802843:ios:3693aa3a8d46232944d33e',
    messagingSenderId: '870510802843',
    projectId: 'to-do-application-442e7',
    storageBucket: 'to-do-application-442e7.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkuEwcX4ul-tlpUVOLB9y_3Eoq4guU1UA',
    appId: '1:870510802843:ios:3c754349fa3faaa244d33e',
    messagingSenderId: '870510802843',
    projectId: 'to-do-application-442e7',
    storageBucket: 'to-do-application-442e7.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
